monkeypatch  # unused variable (tests/test_cli.py:23)
monkeypatch  # unused variable (tests/test_cli.py:33)
monkeypatch  # unused variable (tests/test_cli.py:43)
argtypes  # unused variable (server/iomanager.py:192)
restype  # unused variable (server/iomanager.py:192)
binary_and_args  # unused variable (server/config.py:18)
project_cwd  # unused variable (server/config.py:19)
