monkeypatch  # unused variable (tests/test_cli.py:23)
monkeypatch  # unused variable (tests/test_cli.py:33)
monkeypatch  # unused variable (tests/test_cli.py:43)
argtypes  # unused variable (server/iomanager.py:192)
restype  # unused variable (server/iomanager.py:192)
