site_name: gdbgui
site_description: A browser-based frontend to gdb for C, C++, Go, Rust, and Fortran.

theme:
  name: "material"
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: guptaanurag2106/gdbgui
repo_url: https://github.com/guptaanurag2106/gdbgui
site_url: https://guptaanurag2106.github.io/gdbgui/

nav:
  - Home: "index.md"
  - Screenshot Tour: "screenshots.md"
  - Installation: "installation.md"
  - Getting Started: "gettingstarted.md"
  - Guides: "guides.md"
  - API: "api.md"
  - FAQ: "faq.md"
  - Contributing: "contributing.md"
  - How it Works: "howitworks.md"
  - Changelog: "changelog.md"

markdown_extensions:
  - admonition #  note blocks, warning blocks -- https://github.com/mkdocs/mkdocs/issues/1659
  - markdown.extensions.codehilite:
      guess_lang: false
